version: '3.8'

services:

  db:
    image: mysql:8.0.28-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: Users
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    depends_on: [db]
    restart: always
    ports:
      - 8080:8080

  node:
    image: node:18.1.0-alpine3.15
    command: sh -c "npm install && npm run dev "
    depends_on: [adminer]
    working_dir: /app/src/
    environment:
      MYSQL_DATABASE: Users
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
    ports:
      - 3001:3000
    volumes:
      - ./:/app